#!/bin/bash

set -x
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"

PROJECT_DIR="$DIR/.."

cd ..

find build/graalvm/

xcodebuild -project xcode/MobileTest/MobileTest.xcodeproj -scheme MobileTest -configuration Debug -destination generic/platform=iOS build \
           CODE_SIGN_IDENTITY="" \
           CODE_SIGNING_REQUIRED="NO" \
           CODE_SIGN_ENTITLEMENTS="" \
           CODE_SIGNING_ALLOWED="NO"
