#!/bin/bash

set -x
set -e


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"

PROJECT_DIR="$DIR/.."

export JAVA_HOME="$PROJECT_DIR"/third_party/graalvm-jdk-21.0.3+7.1/Contents/Home
export GRAALVM_HOME="$JAVA_HOME"
export PATH=$JAVA_HOME/bin:$PATH


echo "old $JAVA_CMD"
export JAVA_CMD=$GRAALVM_HOME/bin/java
echo "new $JAVA_CMD"

java -version

cd ..

clojure -T:build uberjar-native-image-shared

mkdir -p library
pushd library

rm -rf ./tmp

sudo xattr -r -d com.apple.quarantine $GRAALVM_HOME/bin/native-image

$GRAALVM_HOME/bin/native-image \
    --verbose \
    --report-unsupported-elements-at-runtime \
    --no-fallback \
    -H:+ExitAfterRelocatableImageWrite \
    -H:+SharedLibrary \
    -H:+AddAllCharsets \
    -H:+ReportExceptionStackTraces \
    -H:-DeadlockWatchdogExitOnTimeout \
    -H:DeadlockWatchdogInterval=0 \
    -H:+RemoveSaturatedTypeFlows \
    -H:-SpawnIsolates \
    -H:PageSize=16384 \
    -Djdk.internal.lambda.eagerlyInitialize=false \
    -H:+ReportExceptionStackTraces \
    -H:TempDirectory="$PROJECT_DIR"/library/tmp \
    -H:ReflectionConfigurationFiles="${PROJECT_DIR}"/conf/reflectionconfig-arm64-ios.json \
    -H:JNIConfigurationFiles="${PROJECT_DIR}"/conf/jniconfig-arm64-ios.json \
    -H:ResourceConfigurationFiles="${PROJECT_DIR}"/conf/resourceconfig-arm64-ios.json \
    --features=clj_easy.graal_build_time.InitClojureClasses \
    -J-Xmx3G \
    -J-XX:MaxDirectMemorySize=2G \
    -J-Dclojure.spec.skip-macros=true \
    -J-Dclojure.compiler.direct-linking=true \
    -J-Dtech.v3.datatype.graal-native=true \
    -Dsvm.targetName=iOS \
    -Dsvm.targetArch=arm64 \
    -H:+UseCAPCache \
    -H:CAPCacheDir="${PROJECT_DIR}"/conf/capcache \
    -H:CompilerBackend=lir \
    '-Dsvm.platform=org.graalvm.nativeimage.Platform$IOS_AARCH64' \
    -jar ../target/bb.jar \


    # -J-Xmx20G \
    # -J-XX:MaxDirectMemorySize=8G \

rm -rf ./build/out
mkdir -p build/out

find ./tmp
find ./tmp -name 'bb.o' -exec ln {} build/out/bb.o \;

find ./tmp -name '*.o' -exec lipo -info {} \;
find ./tmp -name '*.o' -exec file {} \;

lipo -info build/out/bb.o

ar -r build/out/bb.a build/out/*.o
# find ./tmp -name 'grease-uber.o' -exec cp {} build/out \;

popd



