#!/bin/bash
set -x
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"

cd ..



pushd third_party

if ! [ -d graalvm-jdk-21.0.3+7.1 ]; then
    curl -O -sL "https://download.oracle.com/graalvm/21/archive/graalvm-jdk-21.0.3_macos-aarch64_bin.tar.gz"
    sudo xattr -r -d com.apple.quarantine graalvm-jdk-21.0.3_macos-aarch64_bin.tar.gz
    tar xzf graalvm-jdk-21.0.3_macos-aarch64_bin.tar.gz
    rm graalvm-jdk-21.0.3_macos-aarch64_bin.tar.gz
fi

# staticjdk='staticjdk'
# target='ios-arm64'
# version='18-ea+prep18-9'

# fname="${staticjdk}-${target}-gvm-${version}.zip"

# if [ ! -f "$fname" ]; then
#    curl -O "https://download2.gluonhq.com/substrate/staticjdk/${fname}"
#    unzip "$fname"
# fi


# fname="ios-arm64"
# if [ ! -d "$fname" ]; then

#    IOS_LIBS_DIR="$GRAALVM_HOME/lib/svm/clibraries/27/ios-arm64/"

#    if [ -d "$IOS_LIBS_DIR" ]; then
#        ln -s "$IOS_LIBS_DIR" "$fname"
#    else
#        echo "IOS libs not found: $IOS_LIBS_DIR"
#        exit 1
#    fi
# fi

popd
