#!/bin/bash

set -x
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"

PROJECT_DIR="$DIR/.."

export JAVA_HOME="$PROJECT_DIR"/third_party/graalvm-jdk-21.0.3+7.1/Contents/Home
export GRAALVM_HOME="$JAVA_HOME"
export PATH=$JAVA_HOME/bin:$PATH

cd ..

pushd third_party/ios-graal-jdk-21/labs-openjdk/labs-openjdk-21

./configure \
    --with-conf-name=labsjdk \
    --with-version-opt=jvmci-23.1-b37 \
    --with-version-pre= \
    --with-vendor-name="GraalVM Community" \
    --with-vendor-url=https://www.graalvm.org/ \
    --with-vendor-bug-url=https://github.com/oracle/graal/issues \
    --with-vendor-vm-bug-url=https://github.com/oracle/graal/issues

make CONF_NAME=labsjdk graal-builder-image

popd

# prep libffi

pushd third_party/libffi-3.4.8

patch -N ./generate-darwin-source-and-headers.py < ../patches/libffi-only-arm64.patch  || true
python3 ./generate-darwin-source-and-headers.py --only-ios

patch -N ./libffi.xcodeproj/project.pbxproj < ../patches/libffi-only-arm64-2.patch


popd

# automerge
pushd third_party/automerge-js-automerge-3.2.6/rust

cross build --manifest-path automerge-c/Cargo.toml -r --target aarch64-apple-ios

popd
